package org.acme.rest.error;

import java.net.URI;
import java.time.Instant;
import java.util.List;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

/**
 * RFC 7807 (problem+json) response body.
 *
 * <p>The structure is the single API error contract for the gold template (see ADR 0012).
 * All {@code ExceptionMapper}s in this project produce an instance of this record; the
 * media type is always {@link #MEDIA_TYPE}.
 *
 * <p>Fields follow the RFC verbatim, plus two extension members:
 * <ul>
 *   <li>{@code requestId}: the {@code X-Request-Id} header value from the incoming request,
 *       correlated with logs via MDC (see {@link org.acme.rest.filter.RequestIdFilter}).</li>
 *   <li>{@code timestamp}: ISO-8601 instant the error was produced (UTC, server wall-clock).</li>
 *   <li>{@code errors}: used by {@link ConstraintViolationExceptionMapper} to enumerate
 *       per-field validation problems. Null for non-validation errors.</li>
 * </ul>
 *
 * <p>Extensions are allowed by RFC 7807 Section 3.2 provided they do not conflict with the
 * reserved member names; the three above are common and already in use by
 * {@code spring-boot-starter-web} / {@code problem-spring-web} / Quarkus' own
 * {@code RestResponseBuilder}, which keeps client parsers interoperable.
 */
@Schema(
        name = "Problem",
        description = "RFC 7807 application/problem+json error body.",
        examples = {
            """
            {
              "type": "about:blank",
              "title": "Not Found",
              "status": 404,
              "detail": "Product 42 not found",
              "instance": "/products/42",
              "requestId": "8f5a2b20-2c3a-4df0-9c6c-52b21f9a4b63",
              "timestamp": "2026-04-18T12:34:56.789Z"
            }
            """
        })
public record ProblemDetail(
        @Schema(description = "URI reference that identifies the problem type. Defaults to 'about:blank'.",
                examples = {"about:blank"})
                URI type,
        @Schema(description = "Short, human-readable summary of the problem type (does not change per occurrence).",
                examples = {"Not Found"})
                String title,
        @Schema(description = "HTTP status code generated by the origin server for this occurrence.",
                examples = {"404"},
                minimum = "100",
                maximum = "599")
                int status,
        @Schema(description = "Human-readable explanation specific to this occurrence of the problem.",
                examples = {"Product 42 not found"})
                String detail,
        @Schema(description = "URI reference that identifies the specific occurrence (request path).",
                examples = {"/products/42"})
                URI instance,
        @Schema(description = "Correlation id (mirrors X-Request-Id response header and MDC).",
                examples = {"8f5a2b20-2c3a-4df0-9c6c-52b21f9a4b63"})
                String requestId,
        @Schema(description = "Server timestamp (UTC, ISO-8601) when the error was produced.",
                examples = {"2026-04-18T12:34:56.789Z"})
                Instant timestamp,
        @Schema(description = "Per-field validation errors (only populated for 400 from bean validation).")
                List<FieldError> errors) {

    /** The RFC 7807 media type. */
    public static final String MEDIA_TYPE = "application/problem+json";

    /** Default {@code type} value per RFC 7807 §4.2. */
    public static final URI DEFAULT_TYPE = URI.create("about:blank");

    /** Single field validation error (used only for 400 problem responses). */
    @Schema(name = "FieldError", description = "Single bean-validation violation.")
    public record FieldError(
            @Schema(description = "Dotted path to the offending field.", examples = {"price"}) String field,
            @Schema(description = "Violation message.",
                    examples = {"must be greater than or equal to 0"}) String message) {}
}
