-- Initial schema (corresponds to entities: Category, Product, MyEntity).
-- Hibernate in prod/dev after migrations works with strategy=validate (no DDL autogeneration).

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    category_id BIGINT,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id)
);

-- PanacheEntity uses SEQUENCE by default (named MyEntity_SEQ in PostgreSQL).
-- Hibernate / Panache: allocation size defaults to 50 (sequence increment).
CREATE SEQUENCE "MyEntity_SEQ" START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE myentity (
    id BIGINT NOT NULL PRIMARY KEY,
    field VARCHAR(255)
);
