-- Demo catalog: 100 categories + 1050 products (same scale as scripts/seed-data.php).
-- Deterministic; applied by Flyway — no PHP, no running REST API.
-- Dev profile TestDataGenerator skips when category count > 0.

INSERT INTO category (name)
SELECT cat_names[1 + mod(gs - 1, array_length(cat_names, 1))]
FROM generate_series(1, 100) AS g(gs),
     (SELECT ARRAY[
        'Electronics',
        'Laptops',
        'Smartphones',
        'Tablets',
        'Headphones',
        'TVs',
        'Cameras',
        'Game Consoles',
        'Smartwatches',
        'Speakers',
        'Men''s Clothing',
        'Women''s Clothing',
        'Shoes',
        'Accessories',
        'Cameras',
        'Game Consoles',
        'Smartwatches',
        'Speakers',
        'Men''s Clothing',
        'Women''s Clothing',
        'Shoes',
        'Accessories',
        'Sportswear',
        'Furniture',
        'Lighting',
        'Kitchen Appliances',
        'Tableware',
        'Textiles',
        'Books',
        'Toys',
        'Stationery',
        'Musical Instruments',
        'Sports and Fitness',
        'Auto Parts',
        'Tools',
        'Garden',
        'Pets',
        'Beauty and Health',
        'Food',
        'Drinks',
        'Frozen Food',
        'Dairy Products',
        'Bakery',
        'Electronics',
        'Laptops',
        'Smartphones',
        'Tablets',
        'Headphones',
        'TVs',
        'Cameras',
        'Game Consoles',
        'Smartwatches',
        'Speakers',
        'Men''s Clothing',
        'Women''s Clothing',
        'Shoes',
        'Accessories',
        'Sportswear',
        'Furniture',
        'Lighting',
        'Kitchen Appliances',
        'Tableware',
        'Textiles',
        'Books',
        'Toys',
        'Stationery',
        'Musical Instruments',
        'Sports and Fitness',
        'Auto Parts',
        'Tools',
        'Garden',
        'Pets',
        'Beauty and Health',
        'Food',
        'Drinks',
        'Frozen Food',
        'Dairy Products',
        'Bakery',
        'Meat and Fish',
        'Fruits and Vegetables',
        'Snacks',
        'Coffee and Tea',
        'Alcohol',
        'Office Equipment',
        'Networking Equipment',
        'Software',
        'Games',
        'Cables',
        'Jewelry',
        'Watches',
        'Bags',
        'Backpacks',
        'Suitcases',
        'Baby Products',
        'Educational Materials',
        'Puzzles',
        'Board Games',
        'Bicycles',
        'Tourism',
        'Fishing',
        'Skiing',
        'Fitness Equipment',
        'Swimming Pool',
        'Medicines',
        'Vitamins',
        'Coffee',
        'Tea',
        'Bakery',
        'Fruits',
        'Vegetables',
        'Meat',
        'Dairy',
        'Sweets',
        'Beverages',
        'Snacks',
        'Electronics',
        'Computers',
        'Tablets',
        'Smartphones',
        'Headphones',
        'Monitors',
        'Keyboards',
        'Mice',
        'Cables',
        'Adapters',
        'Clothing',
        'Shoes',
        'Bags',
        'Watches',
        'Jewelry',
        'Cosmetics',
        'Perfume',
        'Shampoos',
        'Cream',
        'Conditioners',
        'Washing Machines',
        'Refrigerators',
        'Microwaves',
        'Vacuum Cleaners'
     ]::text[] AS cat_names) AS names;

INSERT INTO product (name, price, category_id)
SELECT
    adj[1 + mod((gs * 7)::int, 15)]
    || ' product '
    || nn[1 + mod((gs * 11)::int, 15)]
    || ' #'
    || gs::text,
    round(((999 + mod(gs * 48611, 4999000))::numeric) / 100, 2),
    1 + mod(gs - 1, 100)
FROM generate_series(1, 1050) AS g(gs),
     (SELECT ARRAY[
        'Premium',
        'Professional',
        'Compact',
        'Smart',
        'Ergonomic',
        'Wireless',
        'Portable',
        'Fast',
        'Quiet',
        'Reliable',
        'Lightweight',
        'Durable',
        'Stylish',
        'Innovative',
        'Colorful'
     ]::text[] AS adj) AS a,
     (SELECT ARRAY[
        'Pro X',
        'Elite',
        'Max Plus',
        'Ultra',
        'Standard',
        'Basic',
        'Advanced',
        '2024',
        'v2',
        'Series 5',
        'Edition',
        'Deluxe',
        'Lite',
        'Air',
        'Neo'
     ]::text[] AS nn) AS n;
